# Tensorflow 6 - 函数与图

In [5]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [1]:
def cube(x):
    return x ** 3

* 使用 Python 值来调用函数：

In [2]:
cube(2)

8

* 使用张量来调用函数：

In [6]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

* 现在将其转化成 TensorFlow 函数：

In [8]:
tf_cube = tf.function(cube)
tf_cube

In [9]:
tf_cube(2) # 返回的将是张量

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [10]:
tf_cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

* 可以使用 @tf.function 修饰：

In [12]:
@tf.function
def tf_cube(x):
    return x ** 3

tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [13]:
tf_cube.python_function(2)

8

* TensorFlow 会优化计算图，因此其计算速度通常会比 python 函数更快。
* Keras 会自动将你的自定义函数转化成 TF 函数 ———— 不需要使用 tf.function。
* 可以通过设置 dynamic=True 可以不将 Python 函数转化成 tf 函数。或者在模型 compile 时设置 run_eagerly=True。